export const items = [
  {
    id: 1,
    category: `animals`,
    title: `Snakes can predict earthquakes`,
    content: `Snakes have the ability of sensing earthquakes as far as 75 miles away. They can sense the earthquake as far as five days before the eathquake occurs.`,
  },
  {
    id: 2,
    category: `humans`,
    title: `More than 7000 people die annually because of doctor's bad handwriting`,
    content: `Reasearch has shown that people actually die due to the bad handwriting of doctors sometimes even the pharmacists cannot see their handwritings.`,
  },
  {
    id: 3,
    category: `humans`,
    title: `Cows often hold grudges against specific people`,
    content: `It will suprise you that cow are excellent at recognizing people's faces and able to remember people for a long time negatively or positively depending on how you treat them.`,
  },
  {
    id: 4,
    category: `animals`,
    title: `If you lift a kangaroo's tail off the ground, it can't hop`,
    content: `Kangaroo use their tail for balance while hoping so if you lift their tail, they will have no balance and fall over.`,
  },
  {
    id: 5,
    category: `humans`,
    title: `Most Korean people do not have armpit odor`,
    content: `Research has shown that only 0.006% of Korean population has the ABCC11 gene. This gene is what causes armpit odor.`,
  },
  {
    id: 6,
    category: `animals`,
    title: `The shortest living animal in the world is Mayfly, it's life span is just 24 hours`,
    content: `Mayfly reproduce and then dies during the short period of 24 hours some live ffor 8-10 hours.`,
  },
  {
    id: 7,
    category: `animals`,
    title: `A cockcroach can live for one week even after chopping it's head off`,
    content: `A headless cockroach has no mouth to drink and will die of dehydration in aroud 7 days.`,
  },
  {
    id: 8,
    category: `humans`,
    title: `About 153,000 people worldwide die everyday`,
    content: `Alot of peole die everyday but double this number are born everyday.`,
  },
  {
    id: 9,
    category: `humans`,
    title: `Dead body swell up like ballon after like four days`,
    content: `This is due to release of gases and liquids. That is why dead body floats in water.`,
  },
  {
    id: 10,
    category: `animals`,
    title: `Elephants are the only animal that cannot jump`,
    content: `The bones in an elephant are all pointed downwards which means they do not have the spring required to push them off the ground.`,
  },
  {
    id: 11,
    category: `humans`,
    title: `The brains can live for hours after death`,
    content: `This is the reason why people who suffer near-fatal accident, heart attacks and other life threatening events and have come back to life can account for what they experienced during this period of clinical death.`,
  },
  {
    id: 12,
    category: `animals`,
    title: `A shrimp's brain is located on it's head`,
    content: `The heart of a shrimp is located on it's thorax just after it's head, but both the head and the thorax are covered with the same exoskeleton that is why the shrimp's thorax can be mistaken as part of the head.`,
  },
  {
    id: 13,
    category: `animals`,
    title: `Octopuses have three hearts`,
    content: `This is part of the consequence of it having blue blood. Two hearts pumps blood through the gills while central heart then circulates the blood to hte rest of the body.`,
  },
  {
    id: 14,
    category: `humans`,
    title: `It's is absolutely possible to die from drinking too much water`,
    content: `This is called hyponatremia, this is when the sodium level falls incredibly low. overhydration has killed many athletes.`,
  },
  {
    id: 15,
    category: `humans`,
    title: `Your hair and nail will appear to keep growing a little bit after you die`,
    content: `They won't actually keep growing but due to skin retracting from hydration, it gives the illusion that they are growing longer.`,
  },
  {
    id: 16,
    category: `humans`,
    title: `Crime investigators used to believe that the image of the muderer could be captured in a victim's eyes`,
    content: `Up till the 20th century, investigators would dissect victims's eyes after death to find the image which would hopefully be stored somewhere in the eyeball but we know today that it is not possible.`,
  },
  {
    id: 17,
    category: `humans`,
    title: `The original London Bridge is now Arizona`,
    content: `The london bridge constructed in 1831 was starting to fall apart in 1960s. As a result the City of London decided to sell it and build another one.`,
  },
  {
    id: 18,
    category: `humans`,
    title: `During your lifetime you will produce enough saliva to fill 50 bathtubs`,
    content: `The average global expectancy is about 72 years. In one hour an average person produce 30ml of saliva, this means that you can produce 18,936 litres of siliva in your liftime which is enough to fill 50 bathtubs.`,
  },
  {
    id: 19,
    category: `animals`,
    title: `A lion's roar can be heard from 5 miles away`,
    content: `A lion can roar as loud as 114 decibels, this is due to the way their vocal cords are shaped.`,
  },
  {
    id: 20,
    category: `humans`,
    title: `On average you can fart enough to fill a party ballon`,
    content: `A fart contains several gasses including hydrogen, nitrogen, carbondioxide, oxygen, and sometimes methane as well.`,
  },
  {
    id: 21,
    category: `humans`,
    title: `The entire surface of your skin is replaced every month`,
    content: `To protect you from infections and germs, your skin will change constanly for better or for worse. Your skin will regenerate itself approximately every 27 days.`,
  },
  {
    id: 22,
    category: `animals`,
    title: `Koalas can sleep for about 22 hours per day`,
    content: `They are considered to be one of the sleepiest animal on earth. They live just two hours for their daily activities.`,
  },
  {
    id: 23,
    category: `humans`,
    title: `Walter Suummerford was struck by lightning 4 times`,
    content: `  Walter summerford is considered to be one of the unluckiest person in history. He was struck by lightning three times and once again after he passed away.`,
  },
  {
    id: 24,
    category: `animals`,
    title: `The most friendly animal is not dog, cat or dolphins`,
    content: `The capybara is the friendliest animal in world despite it's initimidating size. These semi-acquatic animals ae highly social, gentle and friendly. They have a life span of 12 years.`,
  },
  {
    id: 25,
    category: `animals`,
    title: `A rooster, a duck and a sheep were the frist hot air ballon passangers`,
    content: `The designers of hot air balloon decided to test out the hot air balloon on animals before subjecting humans to unknown dangers of flight in a hot air ballon.`,
  },
  {
    id: 26,
    category: `animals`,
    title: `A flamingo's head has to be upside down when it eats`,
    content: `The flamingo uses the bristles at the top of it's beak to filter out the mud and water that gets sucked in along with its actual food. It has to eat upside down otherwise it would be unable to filter its food.`,
  },
  {
    id: 27,
    category: `animals`,
    title: `Only half of dolphin's brain sleeps at a time`,
    content: `Dolphins are mammals and can hold their breath for an exceptionally long time, they do not come up for air from time to time and for this reason, dolphin's brain never fully disengage as it still need to retain enough motor control to occasionally go up to the surface and breath.`,
  },
  {
    id: 28,
    category: `animals`,
    title: `Frogs have a 360 degree visual range`,
    content: `The eyes of frogs are made in such a way that at a given moment they can see everything around them including what is behind them.`,
  },
  {
    id: 29,
    category: `animals`,
    title: `A slug has appoximately 27,000 teeth`,
    content: `This number if teeth is more than that of a shark. Like sharks slugs routinely replace their teeths.`,
  },
  {
    id: 30,
    category: `humans`,
    title: `Without smell apples, potatoes, onions taste the same`,
    content: `Yes, apple, onions and potatoes will tastes the same if you were to block your sense of smell somehow you can try the expreiment at home.`,
  },
];
